const Commands = {
    BROADCAST: 'BROADCAST',
    CONNECTION_CLOSED: 'CONNECTION_CLOSED',
    HANDSHAKE_CONFIRMATION: 'HANDSHAKE_CONFIRMATION',
    HANDSHAKE_REQUEST: 'HANDSHAKE_REQUEST',
    HEARTBEAT_CONFIRMATION: 'HEARTBEAT_CONFIRMATION',
    HEARTBEAT_REQUEST: 'HEARTBEAT_REQUEST',
    MESSAGE: 'MESSAGE'
};

module.exports = Commands;
