const Commands = {
    BROADCAST: 'BROADCAST',
    CLIENT_DISCONNECTED: 'CLIENT_DISCONNECTED',
    HANDSHAKE_CONFIRMATION: 'HANDSHAKE_CONFIRMATION',
    HANDSHAKE_REQUEST: 'HANDSHAKE_REQUEST',
    HEARTBEAT_CONFIRMATION: 'HEARTBEAT_CONFIRMATION',
    HEARTBEAT_REQUEST: 'HEARTBEAT_REQUEST',
    MESSAGE: 'MESSAGE'
};

module.exports = Commands;
