module.exports = {
    ADD_CLIENT: 'ADD_CLIENT',
    DELETE_CLIENT: 'DELETE_CLIENT',
    CREATE_SESSION: 'CREATE_SESSION',
    BROADCAST_REQUEST: 'BROADCAST_REQUEST',
    BROADCAST_RESPONSE: 'BROADCAST_RESPONSE',
    CLIENT_DISCONNECTED: 'CLIENT_DISCONNECTED',
    CREATE_SESSION_REQUEST: 'CREATE_SESSION_REQUEST',
    CREATE_SESSION_RESPONSE: 'CREATE_SESSION_RESPONSE',
    CREDENTIALS_REQUEST: 'CREDENTIALS_REQUEST',
    CREDENTIALS_RESPONSE: 'CREDENTIALS_RESPONSE'
};
