const ActionTypes = {
    CONNECTED_TO_SERVER: 'CONNECTED_TO_SERVER',
    CLIENT_DISCONNECTED: 'CLIENT_DISCONNECTED',
    HANDSHAKE_CONFIRM: 'HANDSHAKE_CONFIRM',
    HANDSHAKE_REQUEST: 'HANDSHAKE_REQUEST',
    HEARTBEAT_CONFIRM: 'HEARTBEAT_CONFIRM',
    HEARTBEAT_REQUEST: 'HEARTBEAT_REQUEST'
};

module.exports = ActionTypes;
