const Protocol = {
    BROADCAST_REQUEST: 'BROADCAST_REQUEST',
    BROADCAST_RESPONSE: 'BROADCAST_RESPONSE',
    CREDENTIALS_REQUEST: 'CREDENTIALS_REQUEST',
    CREDENTIALS_RESPONSE: 'CREDENTIALS_RESPONSE'
};

module.exports = Protocol;
