const RouterCommands = {
    BROADCAST: 'BROADCAST',
    HANDSHAKE_CONFIRMATION: 'HANDSHAKE_CONFIRMATION',
    HANDSHAKE_REQUEST: 'HANDSHAKE_REQUEST',
    HEARTBEAT_CONFIRMATION: 'HEARTBEAT_CONFIRMATION',
    HEARTBEAT_REQUEST: 'HEARTBEAT_REQUEST'
};

module.exports = RouterCommands;
